name: Failure Demo

on:
  workflow_dispatch:

jobs:
  fail_demo:
    runs-on: ubuntu-latest

    steps:
      - name: Before failure
        run: echo "Before failure"

      - name: Intentional failure
        run: wrong-command-demo

      - name: After failure
        run: echo "After failure"
